{
 "title": "Environment Sensors",
 "time": { "from": "2021-12-16T18:29:01.162Z", "to": "2021-12-20T18:29:01.166Z" },
 "templating": {
  "list": [
   { "name": "placement", "label": "Sensor placement", "query": { "query": "label_values(sensor_placement)" } }
  ]
 },
 "panels": [
  { "title": "Measurements $placement", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "placement" },
  {
   "title": "Temperature",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sensor_measurement_temperature_c{sensor_location!=\"\",sensor_placement=\"$placement\"}",
     "legendFormat": "{{sensor_location}}"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sensor_measurement_humidity_percent{sensor_location!=\"\",sensor_placement=\"$placement\"}",
     "legendFormat": "{{sensor_location}}"
    }
   ]
  },
  {
   "title": "CO2",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sensor_measurement_co2_ppm{sensor_placement=\"$placement\"}",
     "legendFormat": "{{sensor_location}}"
    }
   ]
  },
  {
   "title": "CO2",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "expr": "sensor_measurement_co2_ppm{sensor_placement=\"$placement\"}",
     "legendFormat": "{{sensor_location}}"
    }
   ]
  },
  {
   "title": "Graphs $placement",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 110 },
   "repeat": "placement",
   "collapsed": true,
   "panels": [
    {
     "title": "Temperature",
     "type": "timeseries",
     "gridPos": { "h": 15, "w": 12, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "expr": "sensor_measurement_temperature_c{sensor_placement=\"$placement\"}<60",
       "legendFormat": "{{sensor_location}}: {{sensor_model}} ({{sensor_id}})"
      }
     ]
    },
    {
     "title": "Humidity",
     "type": "timeseries",
     "gridPos": { "h": 15, "w": 12, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "humidity" } },
     "targets": [
      {
       "expr": "sensor_measurement_humidity_percent{sensor_placement=\"$placement\"}",
       "legendFormat": "{{sensor_location}}: {{sensor_model}} ({{sensor_id}})"
      }
     ]
    }
   ]
  },
  { "title": "Batteries $placement", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 595 }, "repeat": "placement" },
  {
   "title": "Sensors Battery Status",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 596 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "targets": [
    {
     "expr": "sensor_measurement_battery_ok{sensor_placement=\"$placement\"}"
    }
   ]
  }
 ]
}