name: "build"

on:
  # the 1st condition
  workflow_run:
    workflows: ["re-release"]
    branches: [main]
    types:
      - completed

jobs:
  build_linux:
    permissions:
      contents: write
      packages: write

    name: Build Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # build and publish in parallel: linux/386, linux/amd64, linux/arm64, windows/386, windows/amd64, darwin/amd64, darwin/arm64
        goos: [linux]
        goarch: [amd64, arm, arm64]
    steps:
    - uses: actions/checkout@v3
    - name: Install libusb-dev
      run: sudo apt-get install -y pkg-config libusb-1.0-0-dev
    - uses: wangyoucao577/go-release-action@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        release_tag: latest
        overwrite: true
        extra_files: LICENSE README.md sensor_exporter.json
